version: "3"
services:
  proxy:
    image: nginx:1.19-alpine
    volumes:
      - ./proxy/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${PROXY_PORT}:80"
    depends_on:
      - api
      - webapp
  webapp:
    build: webapp
  api:
    build: api
    depends_on:
      - db
  db:
    image: mongo:4.4.0
    volumes:
      - ./data/db:/data/db
