version: "3"
services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - webapp
  webapp:
    build: webapp
    depends_on:
      - api
  api:
    build: api
    env_file:
      - api/.env
    depends_on:
      - db
  db:
    image: mongo:4.4.0
