version: "3"
services:
  proxy:
    image: nginx:1.19-alpine
    volumes:
      - ./proxy/reverse_proxy.${ENVIRONMENT}.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${PROXY_PORT}:80"
    depends_on:
      - webapp
  webapp:
    build: 
      context: webapp
      dockerfile: Dockerfile.${ENVIRONMENT}
    depends_on:
      - api
  api:
    env_file: api/.env
    build: 
      context: api
      dockerfile: Dockerfile.${ENVIRONMENT}
    depends_on:
      - db
  db:
    image: mongo:4.4.0
