FROM node:14.8.0-alpine

RUN mkdir /webapp
WORKDIR /webapp

RUN npm install -g @angular/cli@9.1.4

COPY . .
RUN npm install

CMD ["ng", "serve", "--host",  "0.0.0.0", "--port", "4200", "--disable-host-check"]
