# stage 1

FROM node:14.8.0-alpine AS my-app-build
WORKDIR /webapp
COPY . .
RUN npm install && npm run build --prod


# stage 2

FROM nginx:1.19-alpine
COPY --from=my-app-build /webapp/dist/webapp /usr/share/nginx/html